import { EXPLODE_EFFECT_CONFIG } from "./displacement/explode.config";
import { POINT_SIZE } from "./points/glPointSize";
import { PLANE_FROM_DIMENSION_EFFECT_CONFIG } from "./points/planeFromDimension";
import { PLANE_FROM_IMAGE_EFFECT_CONFIG } from "./points/planeFromImage";
import { POINT_SIZE_FROM_TEXTURE } from "./points/pointsizeFromTexture";
import { ROTATION_EFFECT_CONFIG } from "./rotation";

export const VERTEX_EFFECTS = {
  NONE: "NONE",
  POINT_SIZE: "POINT_SIZE",
  POINT_SIZE_FROM_TEXTURE: "POINT_SIZE_FROM_TEXTURE",
  EXPLODE: "EXPLODE",
  ROTATION: "ROTATION",
  PLANE_FROM_IMAGE: "PLANE_FROM_IMAGE",
  PLANE_FROM_DIMENSION: "PLANE_FROM_DIMENSION",
};

export const VERTEX_EFFECT_SCHEMA_MAP = {
  [VERTEX_EFFECTS.POINT_SIZE]: POINT_SIZE,
  [VERTEX_EFFECTS.POINT_SIZE_FROM_TEXTURE]: POINT_SIZE_FROM_TEXTURE,
  [VERTEX_EFFECTS.EXPLODE]: EXPLODE_EFFECT_CONFIG,
  [VERTEX_EFFECTS.ROTATION]: ROTATION_EFFECT_CONFIG,
  [VERTEX_EFFECTS.PLANE_FROM_IMAGE]: PLANE_FROM_IMAGE_EFFECT_CONFIG,
  [VERTEX_EFFECTS.PLANE_FROM_DIMENSION]: PLANE_FROM_DIMENSION_EFFECT_CONFIG,
};
