import { FRAG_COLOR_NAME } from "../fragment-effects/fragmentEffects.consts";

export const SHADER_TYPES = {
  VERTEX: "VERTEX",
  FRAGMENT: "FRAGMENT",
};
export const MAIN_START = `void main() { `;

export const MAIN_END = "}";

export const FRAG_COLOR_INSTANTIATION = `vec4 ${FRAG_COLOR_NAME} = vec4(1.0,0,0,1.0);`;

export const FUNCTION_TYPES = {
  VERTEX_ROOT: "VERTEX_ROOT",
  VERTEX_SUB_EFFECT: "VERTEX_SUB_EFFECT",
  FRAGMENT_ROOT: "FRAGMENT_ROOT",
  FRAGMENT_SUB_EFFECT: "FRAGMENT_SUB_EFFECT",
  CONFIGURED_STATIC: "CONFIGURED_STATIC",
  STATIC: "STATIC",
};

export const SHADER_VARIABLE_TYPES = {
  VERTEX_POINT: "VERTEX_POINT",
  FRAGMENT_POINT: "FRAGMENT_POINT",
  GL_POINT_SIZE: "GL_POINT_SIZE",
};
