export const SHADER_TYPES = {
  VERTEX: "VERTEX",
  FRAGMENT: "FRAGMENT",
};
export const MAIN_START = `void main() { `;

export const MAIN_END = "}";

export const FUNCTION_TYPES = {
  VERTEX_ROOT: "VERTEX_ROOT",
  VERTEX_SUB_EFFECT: "VERTEX_SUB_EFFECT",
  FRAGMENT_ROOT: "FRAGMENT_ROOT",
  FRAGMENT_SUB_EFFECT: "FRAGMENT_SUB_EFFECT",
  CONFIGURED_STATIC: "CONFIGURED_STATIC",
  STATIC: "STATIC",
};

export const SHADER_VARIABLE_TYPES = {
  VERTEX_POINT: "VERTEX_POINT",
  FRAGMENT_COLOR: "FRAGMENT_COLOR",
  GL_POINT_SIZE: "GL_POINT_SIZE",
};
