import { Vector3, Vector2 } from "three";

export const SHADER_PROPERTY_VALUE_TYPES = {
  INT: "INT",
  FLOAT: "FLOAT",
  BOOL: "BOOL",
  VEC2: "VEC2",
  VEC3: "VEC3",
  VEC4: "VEC4",
  MAT2: "MAT2",
  MAT3: "MAT3",
  MAT4: "MAT4",
  SAMPLER2D: "SAMPLER2D",
  SAMPLER_CUBE: "SAMPLER_CUBE",
  VOID: "VOID",
  CONST: "CONST",
  STRUCT: "STRUCT",
};

export const SHADER_PROPERTY_TYPES = {
  UNIFORM: "UNIFORM",
  VARYING: "VARYING",
  ATTRIBUTE: "ATTRIBUTE",
};

export const UNIFORM_TO_ASSET_MAPPING_CONFIG = {
  id: "",
  assetId: "",
  relationship: "TEXTURE",
};

export const ASSET_MAPPING_RELATIONSHIPS = {
  TEXTURE: "TEXTURE",
  DIMENSION: "DIMENSION",
  CENTER3D: "CENTER3D",
  VIDEO: "VIDEO",
  VIDEO_STREAM: "VIDEO_STREAM",
};

export const ATTRIBUTE_VALUE_TYPES = {
  SINGLE_VALUE: "SINGLE_VALUE",
  INDEXED: "INDEXED",
  RANDOM_VALUE: "RANDOM_VALUE",
  RANDOMIZED_BINARY: "RANDOMIZED_BINARY",
};
