import { DEFAULT_COLOR } from "./color/color";
import { HALFTONE } from "./color/halftone";
import { TEXTURE_PIXEL_COLOR } from "./color/texturePixelColor";
import { AMBIENT_LIGHT } from "./lights/ambientLight";
import { DIRECTIONAL_LIGHT } from "./lights/directionalLight";
import { POINT_LIGHT } from "./lights/pointLight";
import { TEXTURED_POINT } from "./points/texturedPoint";

export const FRAGMENT_EFFECTS = {
  NONE: "NONE",
  TEXTURE_PIXEL_COLOR: "TEXTURE_PIXEL_COLOR",
  COLOR: "COLOR",
  POINT_LIGHT: "POINT_LIGHT",
  DIRECTIONAL_LIGHT: "DIRECTIONAL_LIGHT",
  AMBIENT_LIGHT: "AMBIENT_LIGHT",
  HALFTONE: "HALFTONE",
  TEXTURED_POINT: "TEXTURED_POINT",
};

export const FRAGMENT_EFFECT_SCHEMA_MAP = {
  [FRAGMENT_EFFECTS.TEXTURE_PIXEL_COLOR]: TEXTURE_PIXEL_COLOR,
  [FRAGMENT_EFFECTS.COLOR]: DEFAULT_COLOR,
  [FRAGMENT_EFFECTS.POINT_LIGHT]: POINT_LIGHT,
  [FRAGMENT_EFFECTS.DIRECTIONAL_LIGHT]: DIRECTIONAL_LIGHT,
  [FRAGMENT_EFFECTS.AMBIENT_LIGHT]: AMBIENT_LIGHT,
  [FRAGMENT_EFFECTS.HALFTONE]: HALFTONE,
  [FRAGMENT_EFFECTS.TEXTURED_POINT]: TEXTURED_POINT,
};
