export const CUSTOM_BUFFER_GEOMETRY_TYPES = {
  EMPTY: "EMPTY",
  DETAILED_PLANE: "DETAILED_PLANE",
  SIMPLE_PLANE: "SIMPLE_PLANE",
};

export const CUSTOM_GEOMETRY_TYPES = [
  CUSTOM_BUFFER_GEOMETRY_TYPES.EMPTY,
  CUSTOM_BUFFER_GEOMETRY_TYPES.DETAILED_PLANE,
  CUSTOM_BUFFER_GEOMETRY_TYPES.SIMPLE_PLANE,
];

export const MESH_TYPES = {
  MESH: "MESH",
  POINTS: "POINTS",
  NONE: "NONE",
};

export const MESH_TRANSFORM_TYPES = {
  SET_UP_QUAD: "SET_UP_QUAD",
  MORPH: "MORPH",
  CUSTOM_ATTRIBUTES: "CUSTOM_ATTRIBUTES",
};
