export const CUSTOM_BUFFER_GEOMETRY_TYPES = {
  QUAD: "QUAD",
  EMPTY: "EMPTY",
  FRAME: "FRAME",
  FULL_QUAD: "FULL_QUAD",
};

export const CUSTOM_GEOMETRY_TYPES = [
  CUSTOM_BUFFER_GEOMETRY_TYPES.QUAD,
  CUSTOM_BUFFER_GEOMETRY_TYPES.EMPTY,
  CUSTOM_BUFFER_GEOMETRY_TYPES.FRAME,
  CUSTOM_BUFFER_GEOMETRY_TYPES.FULL_QUAD,
];

export const MESH_TYPES = {
  MESH: "MESH",
  POINTS: "POINTS",
  NONE: "NONE",
};

export const MESH_TRANSFORM_TYPES = {
  SET_UP_QUAD: "SET_UP_QUAD",
  MORPH: "MORPH",
  CUSTOM_ATTRIBUTES: "CUSTOM_ATTRIBUTES",
};
