import { Asset } from "../../../../assets/types";
import {
  MeshTransformConfig,
  TransformValueConfig,
} from "../../../../config/config.types";
import {
  ASSET_MAPPING_RELATIONSHIPS,
  ATTRIBUTE_VALUE_TYPES,
} from "../../../../config/material/shaders/schema";

// Raw-WebGL port of `applyMeshTransforms` + `setAttributes` from
// src/config/mesh/mesh-transforms/. Differences from the three.js path:
// - We don't honour `transformedMeshIds`; the raw-webgl path renders a single
//   mesh (the fullscreen plane), so every transform's values are baked onto
//   it. Mismatched mesh ids are silently ignored.
// - Only DIMENSION asset relationships are resolved here. VERTEX_POINT and
//   NORMAL require model geometry which the raw-webgl asset path doesn't
//   load yet (see TODO below).
// - Output is plain Float32Array attribute data (not three.js BufferAttribute)
//   so the renderer can upload it directly with gl.bufferData.

export type RawWebglAttribute = {
  // Per-vertex attribute data. Length must equal `vertexCount * itemSize`.
  array: Float32Array;
  // Components per vertex. 1 for floats, 2 for vec2, 3 for vec3, 4 for vec4.
  itemSize: 1 | 2 | 3 | 4;
};

export const buildRawWebglAttributes = (
  meshTransforms: MeshTransformConfig[] | undefined,
  vertexCount: number,
  assets: Asset[],
): Record<string, RawWebglAttribute> => {
  if (!meshTransforms || !meshTransforms.length || vertexCount <= 0) return {};

  const out: Record<string, RawWebglAttribute> = {};
  meshTransforms.forEach((transform) => {
    const resolved = resolveAttributeValues(transform.values ?? {}, assets);
    Object.entries(resolved).forEach(([key, config]) => {
      const attribute = buildAttribute(vertexCount, config);
      if (!attribute) return;
      // Mirror the three.js path's `a_` prefix convention so shader sources
      // generated by the existing generator can reference these attributes by
      // the same name.
      out[`a_${key}`] = attribute;
    });
  });

  return out;
};

// Mirrors `getAttributeValuesFromAssets` in
// src/config/mesh/mesh-transforms/formatMeshTransforms.ts but Three-free and
// scoped to the relationships we can resolve from raw-webgl assets.
const resolveAttributeValues = (
  values: Record<string, TransformValueConfig>,
  assets: Asset[],
): Record<string, TransformValueConfig> =>
  Object.entries(values).reduce<Record<string, TransformValueConfig>>(
    (acc, [key, config]) => {
      const { value, type } = config;
      if (
        value &&
        typeof value === "object" &&
        "assetId" in value &&
        "relationship" in value
      ) {
        const { assetId, relationship } = value as {
          assetId: string;
          relationship: string;
        };
        const asset = assets.find((a) => a.guid === assetId);
        if (asset) {
          if (relationship === ASSET_MAPPING_RELATIONSHIPS.DIMENSION) {
            const dim = getAssetDimension(asset);
            if (dim) {
              acc[key] = { ...config, value: dim, type, relationship };
              return acc;
            }
          }
          // TODO: Resolve VERTEX_POINT / NORMAL relationships once raw-webgl
          // assets include 3D geometry data (the three.js path uses
          // `getAssetGeometry` -> `getVertices`/`getNormals`).
          acc[key] = { ...config, value, type, relationship };
          return acc;
        }
      }
      acc[key] = config;
      return acc;
    },
    {},
  );

const getAssetDimension = (asset: Asset): [number, number] | null => {
  // ImageBitmap (the only asset data shape currently produced by the
  // raw-webgl asset path) exposes width/height directly.
  const data = asset.data as { width?: number; height?: number } | undefined;
  if (
    data &&
    typeof data.width === "number" &&
    typeof data.height === "number"
  ) {
    return [data.width, data.height];
  }
  return null;
};

const buildAttribute = (
  vertexCount: number,
  { type, value, relationship }: TransformValueConfig,
): RawWebglAttribute | null => {
  if (!type) return null;
  switch (type) {
    case ATTRIBUTE_VALUE_TYPES.INDEXED: {
      const arr = new Float32Array(vertexCount);
      for (let i = 0; i < vertexCount; i += 1) arr[i] = i;
      return { array: arr, itemSize: 1 };
    }
    case ATTRIBUTE_VALUE_TYPES.RANDOM_VALUE: {
      const arr = new Float32Array(vertexCount);
      for (let i = 0; i < vertexCount; i += 1) arr[i] = Math.random();
      return { array: arr, itemSize: 1 };
    }
    case ATTRIBUTE_VALUE_TYPES.SINGLE_RANDOM_VALUE: {
      const arr = new Float32Array(vertexCount);
      arr.fill(Math.random());
      return { array: arr, itemSize: 1 };
    }
    case ATTRIBUTE_VALUE_TYPES.RANDOMIZED_BINARY: {
      const arr = new Float32Array(vertexCount);
      const probability = typeof value === "number" ? value : 0.5;
      for (let i = 0; i < vertexCount; i += 1) {
        arr[i] = Math.random() < probability ? 1 : 0;
      }
      return { array: arr, itemSize: 1 };
    }
    case ATTRIBUTE_VALUE_TYPES.SINGLE_VALUE:
      return buildSingleValueAttribute(vertexCount, value, relationship);
    // TODO: ATTRIBUTE_VALUE_TYPES.QUAD - the three.js setAttributes has no
    // case for it either; port once that path is implemented.
    default:
      return null;
  }
};

const buildSingleValueAttribute = (
  vertexCount: number,
  value: unknown,
  relationship?: string,
): RawWebglAttribute | null => {
  // VERTEX_POINT / NORMAL: value is expected to be a flat ArrayLike<number>
  // of `vertexCount * 3` floats (matching the three.js BufferAttribute(value, 3)
  // path). Currently unreachable in raw-webgl because we don't load model
  // geometry; left here so behaviour matches once that lands.
  if (
    relationship === ASSET_MAPPING_RELATIONSHIPS.VERTEX_POINT ||
    relationship === ASSET_MAPPING_RELATIONSHIPS.NORMAL
  ) {
    if (value instanceof Float32Array) return { array: value, itemSize: 3 };
    if (ArrayBuffer.isView(value) || Array.isArray(value)) {
      return {
        array: new Float32Array(value as ArrayLike<number>),
        itemSize: 3,
      };
    }
    return null;
  }

  // DIMENSION: resolved earlier into [width, height]; broadcast across all
  // vertices as a per-vertex vec2.
  if (
    relationship === ASSET_MAPPING_RELATIONSHIPS.DIMENSION &&
    Array.isArray(value) &&
    value.length === 2 &&
    typeof value[0] === "number" &&
    typeof value[1] === "number"
  ) {
    const arr = new Float32Array(vertexCount * 2);
    for (let i = 0; i < vertexCount; i += 1) {
      arr[i * 2 + 0] = value[0] as number;
      arr[i * 2 + 1] = value[1] as number;
    }
    return { array: arr, itemSize: 2 };
  }

  // Plain numeric single value: fill an itemSize-1 buffer.
  if (typeof value === "number") {
    const arr = new Float32Array(vertexCount);
    arr.fill(value);
    return { array: arr, itemSize: 1 };
  }

  return null;
};
