import { IMAGE_TO_POINTS_EFFECT_CONFIG } from "./effects/points/imageToPoints.config";
import { INTERACTIVE_EFFECTS } from "../constants/interactiveEffects.consts";
import { EXPLODE_EFFECT_CONFIG } from "./effects/explode.config";
import { ROTATION_EFFECT_CONFIG } from "./effects/rotationEffect.config";
import { AFFECTED_POSITION_EFFECT_CONFIG } from "./effects/affectedPosition.config";
import { POINT_SIZE_EFFECT_CONFIG } from "./effects/points/glPointSize.config";
import { POINT_SIZE_EFFECT_CONFIG as POINT_SIZE_FROM_TEXTURE_EFFECT_CONFIG } from "./effects/points/pointsizeFromTexture";
import { PLANE_FROM_IMAGE_EFFECT_CONFIG } from "./effects/points/planeFromImage";

export const VERTEX_POINT_NAME = "currentVertexPoint";
export const VERTEX_NORMAL_NAME = "currentVertexNormal";
export const VERTEX_POINT_INSTANTIATION = `vec4 ${VERTEX_POINT_NAME} = vec4(position.xyz, 1.0);`;
export const VERTEX_NORMAL_INSTANTIATION = `vec4 ${VERTEX_NORMAL_NAME} = vec4(normal.xyz, 1.0);`;

export const VERTEX_EFFECTS = {
  NONE: "NONE",
  POINT_SIZE: "POINT_SIZE",
  POINT_SIZE_FROM_TEXTURE: "POINT_SIZE_FROM_TEXTURE",
  EXPLODE: "EXPLODE",
  IMAGE_TO_POINTS: "IMAGE_TO_POINTS",
  ROTATION: "ROTATION",
  PLANE_FROM_IMAGE: "PLANE_FROM_IMAGE",
  ...INTERACTIVE_EFFECTS,
};

export const VERTEX_EFFECT_CONFIG_MAP = {
  [VERTEX_EFFECTS.POINT_SIZE]: POINT_SIZE_EFFECT_CONFIG,
  [VERTEX_EFFECTS.POINT_SIZE_FROM_TEXTURE]:
    POINT_SIZE_FROM_TEXTURE_EFFECT_CONFIG,
  [VERTEX_EFFECTS.IMAGE_TO_POINTS]: IMAGE_TO_POINTS_EFFECT_CONFIG,
  [VERTEX_EFFECTS.EXPLODE]: EXPLODE_EFFECT_CONFIG,
  [VERTEX_EFFECTS.AFFECTED_POSITION]: AFFECTED_POSITION_EFFECT_CONFIG,
  [VERTEX_EFFECTS.ROTATION]: ROTATION_EFFECT_CONFIG,
  [VERTEX_EFFECTS.PLANE_FROM_IMAGE]: PLANE_FROM_IMAGE_EFFECT_CONFIG,
};
