export const SHADER_SCHEMA_TYPES = {
  OPERATOR: "OPERATOR",
  VERTEX: "VERTEX",
  FRAGMENT: "FRAGMENT",
  FUNCTION: "FUNCTION",
  MESH_TRANSFORM: "MESH_TRANSFORM",
};

export const SHADER_PROPERTY_VALUE_TYPES = {
  INT: "INT",
  FLOAT: "FLOAT",
  BOOL: "BOOL",
  VEC2: "VEC2",
  VEC3: "VEC3",
  VEC4: "VEC4",
  MAT2: "MAT2",
  MAT3: "MAT3",
  MAT4: "MAT4",
  SAMPLER2D: "SAMPLER2D",
  SAMPLER_CUBE: "SAMPLER_CUBE",
  VOID: "VOID",
  CONST: "CONST",
  STRUCT: "STRUCT",
};

export const SHADER_PROPERTY_TYPES = {
  CONSTANT: "CONSTANT",
  UNIFORM: "UNIFORM",
  VARYING: "VARYING",
  ATTRIBUTE: "ATTRIBUTE",
  MESH_TRANSFORM_VALUE: "MESH_TRANSFORM_VALUE",
  SHADER_VARIABLE: "SHADER_VARIABLE",
};

export const ASSET_MAPPING_RELATIONSHIPS = {
  TEXTURE: "TEXTURE",
  DIMENSION: "DIMENSION",
  CENTER3D: "CENTER3D",
  VIDEO: "VIDEO",
  VIDEO_STREAM: "VIDEO_STREAM",
};

export const ATTRIBUTE_VALUE_TYPES = {
  SINGLE_VALUE: "SINGLE_VALUE",
  INDEXED: "INDEXED",
  RANDOM_VALUE: "RANDOM_VALUE",
  RANDOMIZED_BINARY: "RANDOMIZED_BINARY",
};

export const VARYING_TYPES = {
  DEFAULT: "DEFAULT",
  ATTRIBUTE: "ATTRIBUTE",
  CUSTOM: "CUSTOM",
  BINARY: "BINARY",
  PARAMETER_FUNCTION: "PARAMETER_FUNCTION",
};

export const SHADER_VARIABLE_TYPES = {
  VERTEX_POINT: "VERTEX_POINT",
  FRAGMENT_COLOR: "FRAGMENT_COLOR",
  DISCARD_COLOR: "DISCARD_COLOR",
  GL_POINT_SIZE: "GL_POINT_SIZE",
  POSITION: "POSITION",
  LIGHT: "LIGHT",
};

export const SHADER_PROPERTY_TAGS = {
  COLOR: "color",
};

export const SHADER_TYPES = {
  VERTEX: SHADER_SCHEMA_TYPES.VERTEX,
  FRAGMENT: SHADER_SCHEMA_TYPES.FRAGMENT,
};

export const SHADER_VARIABLE_ASSIGNMENT_KEYS = {
  VERTEX_POINT: "pointPosition",
  FRAGMENT_COLOR: "fragColor",
  LIGHT: "light",
};
