// import { AND_OPERATOR_SCHEMA } from "./andFunction";
import { SPLIT_VALUE_OPERATOR_SCHEMA } from "./splitValue";
// import { SEQUENCE_OPERATOR_SCHEMA } from "./sequence";

export const OPERATOR_TYPES = {
  AND: "AND",
  SPLIT_VALUE: "SPLIT_VALUE",
  DEFAULT: "DEFAULT",
  SEQUENCE: "SEQUENCE",
};

export const OPERATOR_SCHEMA_MAP = {
  // [OPERATOR_TYPES.AND]: AND_OPERATOR_SCHEMA,
  [OPERATOR_TYPES.SPLIT_VALUE]: SPLIT_VALUE_OPERATOR_SCHEMA,
  // [OPERATOR_TYPES.SEQUENCE]: SEQUENCE_OPERATOR_SCHEMA,
};
