import type { ParameterConfig } from "../types";
import { FRAGMENT_LIGHT_GROUP_TYPE } from "./consts";
import {
  createEmptyFragmentLight,
  defaultFragmentLightId,
  populateFragmentLightSlots,
} from "./lightSlots";
import type { ShaderEffectLightConfig } from "./types";

export type FragmentLightGroupResult = {
  parameters: ParameterConfig[];
  light: ShaderEffectLightConfig;
};

/**
 * Creates a fully populated STANDARD light group (position, strength, color)
 * with autoGenerated parameters. Prefer createEmptyFragmentLight +
 * populateFragmentLightSlots for incremental UI flows.
 */
export const createFragmentLightGroup = (
  lightName: string,
  createId: () => string = defaultFragmentLightId,
): FragmentLightGroupResult => {
  const empty = createEmptyFragmentLight(lightName, createId);
  const { light, newParameters } = populateFragmentLightSlots(
    empty,
    FRAGMENT_LIGHT_GROUP_TYPE.STANDARD,
    createId,
  );
  return {
    parameters: newParameters,
    light,
  };
};
