import {
  SHADER_PROPERTY_TYPES,
  SHADER_PROPERTY_VALUE_TYPES,
} from "../consts";
import type { ParameterConfig } from "../types";
import {
  CONTROLLER_TYPE,
  FRAGMENT_LIGHT_GROUP_TYPE,
  FRAGMENT_LIGHT_SLOT,
} from "./consts";
import type { ParameterControlConfig, ShaderEffectLightConfig } from "./types";

export type FragmentLightSlotKey =
  (typeof FRAGMENT_LIGHT_SLOT)[keyof typeof FRAGMENT_LIGHT_SLOT];

export type FragmentLightGroupTypeId =
  (typeof FRAGMENT_LIGHT_GROUP_TYPE)[keyof typeof FRAGMENT_LIGHT_GROUP_TYPE];

export type FragmentLightSlotDefinition = {
  slotKey: FragmentLightSlotKey;
  nameSuffix: string;
  allowedValueTypes: string[];
  defaultValue: unknown;
  controlsConfig: ParameterControlConfig;
};

export type FragmentLightGroupTypeDefinition = {
  id: FragmentLightGroupTypeId;
  label: string;
  slots: FragmentLightSlotDefinition[];
};

export const FRAGMENT_LIGHT_SLOT_DEFINITIONS: Record<
  FragmentLightSlotKey,
  FragmentLightSlotDefinition
> = {
  [FRAGMENT_LIGHT_SLOT.POSITION]: {
    slotKey: FRAGMENT_LIGHT_SLOT.POSITION,
    nameSuffix: "Position",
    allowedValueTypes: [SHADER_PROPERTY_VALUE_TYPES.VEC3],
    defaultValue: [1, 1, 1],
    controlsConfig: {
      controllerType: CONTROLLER_TYPE.POSITION,
      controllerConfig: { selectable: true },
    },
  },
  [FRAGMENT_LIGHT_SLOT.STRENGTH]: {
    slotKey: FRAGMENT_LIGHT_SLOT.STRENGTH,
    nameSuffix: "Strength",
    allowedValueTypes: [SHADER_PROPERTY_VALUE_TYPES.FLOAT],
    defaultValue: 1,
    controlsConfig: {
      controllerType: CONTROLLER_TYPE.SLIDER,
      controllerConfig: {
        dimensions: [{ lowerBound: 0, upperBound: 1, step: 0.1 }],
      },
    },
  },
  [FRAGMENT_LIGHT_SLOT.COLOR]: {
    slotKey: FRAGMENT_LIGHT_SLOT.COLOR,
    nameSuffix: "Color",
    allowedValueTypes: [SHADER_PROPERTY_VALUE_TYPES.VEC3],
    defaultValue: [1, 1, 1],
    controlsConfig: {
      controllerType: CONTROLLER_TYPE.COLOR,
    },
  },
};

export const FRAGMENT_LIGHT_GROUP_TYPES: Record<
  FragmentLightGroupTypeId,
  FragmentLightGroupTypeDefinition
> = {
  [FRAGMENT_LIGHT_GROUP_TYPE.STANDARD]: {
    id: FRAGMENT_LIGHT_GROUP_TYPE.STANDARD,
    label: "Standard",
    slots: [
      FRAGMENT_LIGHT_SLOT_DEFINITIONS[FRAGMENT_LIGHT_SLOT.POSITION],
      FRAGMENT_LIGHT_SLOT_DEFINITIONS[FRAGMENT_LIGHT_SLOT.STRENGTH],
      FRAGMENT_LIGHT_SLOT_DEFINITIONS[FRAGMENT_LIGHT_SLOT.COLOR],
    ],
  },
};

export const defaultFragmentLightId = (): string => {
  if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
    return crypto.randomUUID().replace(/-/g, "");
  }
  return `id_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 10)}`;
};

export const getLightSlotParameterId = (
  light: ShaderEffectLightConfig,
  slotKey: FragmentLightSlotKey,
): string | undefined => light[slotKey]?.parameterId;

export const isParameterCompatibleWithSlot = (
  parameter: Pick<ParameterConfig, "valueType">,
  slotDef: FragmentLightSlotDefinition,
): boolean => slotDef.allowedValueTypes.includes(parameter.valueType);

export const createEmptyFragmentLight = (
  lightName: string,
  createId: () => string = defaultFragmentLightId,
): ShaderEffectLightConfig => ({
  id: createId(),
  name: lightName.trim() || "Light",
});

export const createParameterForSlot = (
  lightName: string,
  slotDef: FragmentLightSlotDefinition,
  createId: () => string = defaultFragmentLightId,
): ParameterConfig => {
  const guid = createId();
  const name = `${lightName.trim() || "Light"}_${slotDef.nameSuffix}`;
  return {
    guid,
    key: guid,
    name,
    type: "parameter",
    valueType: slotDef.allowedValueTypes[0] as ParameterConfig["valueType"],
    value: slotDef.defaultValue,
    parameterType:
      SHADER_PROPERTY_TYPES.UNIFORM as keyof typeof SHADER_PROPERTY_TYPES,
    autoGenerated: true,
    controlsConfig: slotDef.controlsConfig,
  };
};

export type PopulateFragmentLightResult = {
  light: ShaderEffectLightConfig;
  newParameters: ParameterConfig[];
};

/**
 * Fill empty slots on a light for the given group type.
 * Only creates parameters for slots that are not already bound.
 */
export const populateFragmentLightSlots = (
  light: ShaderEffectLightConfig,
  groupTypeId: FragmentLightGroupTypeId = FRAGMENT_LIGHT_GROUP_TYPE.STANDARD,
  createId: () => string = defaultFragmentLightId,
): PopulateFragmentLightResult => {
  const groupType =
    FRAGMENT_LIGHT_GROUP_TYPES[groupTypeId] ??
    FRAGMENT_LIGHT_GROUP_TYPES[FRAGMENT_LIGHT_GROUP_TYPE.STANDARD];

  const nextLight: ShaderEffectLightConfig = { ...light };
  const newParameters: ParameterConfig[] = [];

  for (const slotDef of groupType.slots) {
    if (getLightSlotParameterId(nextLight, slotDef.slotKey)) continue;
    const parameter = createParameterForSlot(nextLight.name, slotDef, createId);
    newParameters.push(parameter);
    nextLight[slotDef.slotKey] = { parameterId: parameter.guid };
  }

  return { light: nextLight, newParameters };
};

/** Collect all parameter guids currently referenced by a light's slots. */
export const collectLightParameterIds = (
  light: ShaderEffectLightConfig,
): string[] => {
  const ids: string[] = [];
  for (const slotKey of Object.values(FRAGMENT_LIGHT_SLOT)) {
    const id = getLightSlotParameterId(light, slotKey);
    if (id) ids.push(id);
  }
  return ids;
};

/** Ensure older configs without `id` get a stable id at load time. */
export const ensureFragmentLightId = (
  light: ShaderEffectLightConfig,
  createId: () => string = defaultFragmentLightId,
): ShaderEffectLightConfig => {
  if (light.id) return light;
  return { ...light, id: createId() };
};
